ApplicationPL/Controllers/DepartmentController.cs
using ApplicationBLL.Interfaces;
using ApplicationDAL.Models;
using ApplicationPL.Models;
using AutoMapper;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using System.Collections.Generic;

namespace ApplicationPL.Controllers
{
    [Authorize]
    public class DepartmentController : Controller
    {
        private readonly IUnitOfWork _unitOfWork;

        private readonly IMapper _mapper;   

        public DepartmentController(IUnitOfWork unitOfWork , IMapper mapper)
        {
            _unitOfWork = unitOfWork;
            _mapper = mapper;
        }

        [HttpGet]
        public async Task<IActionResult> Index()
        {

            //Get all Department
            IEnumerable<Department> models = await _unitOfWork.DepartmentRepository.ShowAllAsync();

            //Convert it to Ienumrable of DepartmentViewModel
            IEnumerable<DepartmentViewModel> depts = _mapper.Map<IEnumerable<Department>, IEnumerable<DepartmentViewModel>>(models);


            return View(model: depts);
        }

        [HttpGet]
        public IActionResult Create()
        {
            return View("Create");
        }

        [HttpPost]
        public async Task<IActionResult> Create(Department dept)
        {
            //Check if the Model is not Null

            if (ModelState.IsValid)
            {
                var resultNumber = await _unitOfWork.DepartmentRepository.AddAsync(dept);
                if (resultNumber > 0)
                {
                    return RedirectToAction("Index");
                }
            }

            return View(dept);
        }

        public async Task<IActionResult> Details(int? id)
        {
            if (id is null)
            {
                return BadRequest();
            }
            else
            {
                Department dept = await _unitOfWork.DepartmentRepository.GetAsync(id.Value);

                if (dept is null) return NotFound();

                return View(dept);
            }
        }

        [HttpGet]
        public async Task<IActionResult>  Update(int? id)
        {
            if (id is null)
            {
                return BadRequest();
            }
            Department dept = await _unitOfWork.DepartmentRepository.GetAsync(id.Value);
            return View(model: dept);
        }

       
        public async Task<IActionResult> Edit(int id, Department dept)

        {
            Department returnedDept = await _unitOfWork.DepartmentRepository.GetAsync(id);

            
           
            if (returnedDept != null)
            {
                if (ModelState.IsValid)
                {

                    returnedDept.Code = dept.Code;
                    returnedDept.Name = dept.Name;
                    returnedDept.DateOfCreation = dept.DateOfCreation;

                    _unitOfWork.Save();

                    return RedirectToAction("Index");

                }
            }

            return View("Update", dept);
    
        }

        public async Task<IActionResult> Delete(int id) 
        {
           Department dept = await _unitOfWork.DepartmentRepository.GetAsync(id);
            _unitOfWork.DepartmentRepository.Delete(dept);
            return RedirectToAction("Index");
        }

        
       //public IActionResult Test(string name, int age , string[] colors) 
       // {
       //     var result = Request.QueryString.ToString();
       //     Console.WriteLine(result);
       //     return Content($"{name} {age}");
       // }
    }

    
}

ApplicationPL/Controllers/EmployeeController.cs
using ApplicationBLL.Interfaces;
using ApplicationDAL.Models;
using ApplicationPL.Helpers;
using ApplicationPL.Models;
using AutoMapper;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;

namespace ApplicationPL.Controllers
{
    [Authorize]
    public class EmployeeController : Controller
    {

        private IMapper _mapper;

        private IUnitOfWork _unit { get; }

        public EmployeeController(IUnitOfWork unit , IMapper mapper)
        {
            _unit = unit;
            _mapper = mapper;
        }

        public IActionResult UniqueName(string Name) 
        {
            if (Name.Contains("route")) 
            {
                return Json(true);
            }
            else 
            { 
                return Json(false);
            }
        }

        public async Task<IActionResult> Index()
        {
            IEnumerable<Employee> list = await _unit.EmployeeRepository.ShowAllAsync();

            IEnumerable<EmployeeViewModel> mappedEmps = _mapper.Map<IEnumerable<Employee>,IEnumerable<EmployeeViewModel>>(list);

            return View(model: mappedEmps);
        }

        [HttpPost]
        public async Task<IActionResult>  Index(string searchedName)
        {

            //Searching Task
            //1 - Create Form that has input and search button 
            //2 - If the value is wrong or null -> show all Employee 
            //3 - if the value is not null -> search for all emps that contains this name
            //Get name from user Form
            //Check for null 
            if (string.IsNullOrEmpty(searchedName)) 
            {
                IEnumerable<Employee> list = await _unit.EmployeeRepository.ShowAllAsync();

                IEnumerable<EmployeeViewModel> mappedEmps = _mapper.Map<IEnumerable<Employee>, IEnumerable<EmployeeViewModel>>(list);

                return View(model: mappedEmps);
            }
            else 
            {
                IEnumerable<Employee> searchedEmps = await _unit.EmployeeRepository.SearchEmpsAsync(searchedName);

                IEnumerable<EmployeeViewModel> mappedEmps = _mapper.Map<IEnumerable<Employee>, IEnumerable<EmployeeViewModel>>(searchedEmps);

                return View(mappedEmps);
            }
        }
        

        public async Task<IActionResult>  Details(int id) 
        {
            Employee emp = await _unit.EmployeeRepository.GetAsync(id);

            EmployeeViewModel mappedEmp = _mapper.Map<Employee, EmployeeViewModel>(emp);

            return View(mappedEmp);
        }

        public async Task<IActionResult> Update(int id) 
        {
            //Get the Employee That we pressed on 
            Employee emp = await _unit.EmployeeRepository.GetAsync(id);

            EmployeeViewModel mappedEmp = _mapper.Map<Employee, EmployeeViewModel>(emp);

            var deptsInfo = _unit.DepartmentRepository.ShowAllAsync();


            ViewBag.Depts = new SelectList(await _unit.DepartmentRepository.ShowAllAsync(),"Id","Name");


            //Send session Informations 
            HttpContext.Session.SetString("Name", mappedEmp.Name);
            HttpContext.Session.SetInt32("Age", mappedEmp.Age);


            return View(mappedEmp);
        }

        [HttpPost]
        public async Task<IActionResult>  Edit([FromRoute] int id,EmployeeViewModel empVM) 
        {
            ViewBag.Depts = new SelectList(_unit.DepartmentRepository.ShowAllAsync().Result, "Id", "Name");


            //Get Img name from Database Based on Emp
            Employee Emp =await _unit.EmployeeRepository.GetAsync(empVM.Id);
            string oldImgName = Emp.Img;

          
            if (ModelState.IsValid) 
            {

                //Delete old image
                if(empVM.Image != null) 
                {

                DocumentHelper.Delete(oldImgName, "Imgs");

                string newFileName = DocumentHelper.Upload(empVM.Image,"Imgs");

                empVM.Img = newFileName;
                }
                //Upload new Image

                Employee mappedEmp = _mapper.Map<EmployeeViewModel, Employee>(empVM);
                

                _unit.EmployeeRepository.Update(mappedEmp);


                return RedirectToAction("Index");
            }

            return View("Update",empVM);
         }

        public async Task<IActionResult> Delete(int id) 
        {
            Employee emp = await _unit.EmployeeRepository.GetAsync(id);

            if(emp != null) 
            {
                int statusNumber = _unit.EmployeeRepository.Delete(emp);

                  _unit.Save();

                if(statusNumber > 0 && emp.Img != null) 
                {
                    DocumentHelper.Delete(emp.Img,"Imgs");
                }

                return RedirectToAction("Index");
            }

            return RedirectToAction("Index");
            
        }

        public async Task<IActionResult> Add() 
        {
            ViewBag.Depts = new SelectList(_unit.DepartmentRepository.ShowAllAsync().Result, "Id", "Name");
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Add(EmployeeViewModel EmpVm) 
        {

            if (ModelState.IsValid) 
            {

               if(EmpVm.Image != null) 
                {
                    string fileName = DocumentHelper.Upload(EmpVm.Image, "imgs");
                    EmpVm.Img = fileName;
                }

                Employee mappedEmp = _mapper.Map<EmployeeViewModel, Employee>(EmpVm);

                await _unit.EmployeeRepository.AddAsync(mappedEmp);
                _unit.Save();      
                return RedirectToAction("Index");
            }
            else 
            {
                
                return View(EmpVm);
            }

            
        }


        public IActionResult Test() 
        {
            //Catch session 

            string userName = HttpContext.Session.GetString("Name");
            int? userAge = HttpContext.Session.GetInt32("Age");

            return Content($"Name: {userName} - Age: {userAge}");
        }
    }
}
 

ApplicationPL/Views/Shared/AuthLayout.cshtml
<!DOCTYPE html>
<html>
<head>
	<title>@ViewData["Title"]</title>
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
	<script type="application/x-javascript"> addEventListener("load", function() { setTimeout(hideURLbar, 0); }, false); function hideURLbar(){ window.scrollTo(0,1); } </script>
	<!-- Custom Theme files -->
	<link href="~/css/style.css" rel="stylesheet" type="text/css" media="all" />
	<!-- //Custom Theme files -->
	<!-- web font -->
	<link href="//fonts.googleapis.com/css?family=Roboto:300,300i,400,400i,700,700i" rel="stylesheet">
	<!-- //web font -->
</head>
<body>
	<!-- main -->
	<div class="main-w3layouts wrapper">
		<h1>@ViewData["Header"]</h1>


		@RenderBody()
		
		<div class="colorlibcopy-agile">
			<p>© 2024 Ebrahem Ashraf. All rights reserved </p>
		</div>
		<!-- //copyright -->
		<ul class="colorlib-bubbles">
			<li></li>
			<li></li>
			<li></li>
			<li></li>
			<li></li>
			<li></li>
			<li></li>
			<li></li>
			<li></li>
			<li></li>
		</ul>
	</div>
	<!-- //main -->
	<script src="~/lib/jquery/dist/jquery.min.js"></script>
	<script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
	@await RenderSectionAsync("ValidationSection", required: false)
</body>
</html>

ApplicationPL/Views/Shared/_ButtonPartial.cshtml
@model object
<td><a class="btn btn-success" asp-action="Details" asp-route-id="@Model">Details</a></td>
<td><a class="btn btn-warning" asp-action="Update" asp-route-id="@Model">Update</a></td>
<td><a class="btn btn-danger" asp-action="Delete" asp-route-id="@Model">Delete</a></td>

ApplicationPL/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - CRUD</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/ApplicationPL.styles.css" asp-append-version="true" />
    <link href="~/font/font-awesome-4.7.0/css/font-awesome.min.css" rel="stylesheet" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">CRUD</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Department" asp-action="Index">Department</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Employee" asp-action="Index">Employee</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container" style="text-align:center">
            &copy; 2024 - Ebrahem Ashraf - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("ValidationSection", required: false)
</body>
</html>